### ISSUE TITLE
potential bug at connection matrix

### ISSUE THREAD

**Issue by izziiyt** [WorksApplications/Sudachi#108]
@kazuma-t 

row and column of connection matrix looks traversed and I think `setConnectionCost` at `GrammerImpl` contains bug.

1. `setConnectionCost` looks properly used (rightid is right, leftid is left)
https://github.com/WorksApplications/Sudachi/blob/979404db6511b99758dfcf5178bf278e6c45adc7/src/main/java/com/worksap/nlp/sudachi/EditConnectionCostPlugin.java#L79

2. `getConnectionCost` looks not properly used (rightid is left, leftid is right)
https://github.com/WorksApplications/Sudachi/blob/979404db6511b99758dfcf5178bf278e6c45adc7/src/main/java/com/worksap/nlp/sudachi/LatticeImpl.java#L125

`setConnectionCost` is not frequently used, so the effect is small.
It's better to have consensus between 1 and 2 and shape of connection matrix.
Off course, the format of dictionary file must be kept.

**Comment by kazuma-t** [comment]
The code is correct but confusing.

2 means to get the cost between the right side of the left node and the left side of the right node.
This is very true.

The names of parameters are misleading in `Grammar#getConnectionCost` and `Grammar#setConnectionCost`. In these methods `leftId` means the right side of the left node and `rightId` is the opposite. This naming is so evil. I'll change it.
