### ISSUE TITLE
Blank reading form in OOV

### ISSUE THREAD

**Issue by hondv** [WorksApplications/Sudachi#126]
Currently,  unknown (OOV) words have the same reading form is blank string ("") 

Can u have any solutions to Unknown words can return itself in reading form ?

example:
text: `サンドウィッチマン ライブ`
output:
```
 text               POS               Base_form          Reading_form
 サンドウィッチマン  名詞-普通名詞-一般   サンドウィッチマン   
 ライブ            名詞-普通名詞-一般   ライブ             ライブ
```

expect:
```
 text               POS               Base_form          Reading_form
 サンドウィッチマン  名詞-普通名詞-一般   サンドウィッチマン   サンドウィッチマン
 ライブ            名詞-普通名詞-一般   ライブ             ライブ
```

I suggest a solution is adding a flag in `SimpleOovProviderPlugin` to check when the unknown words return itself in reading form:
  ```

  @Override
     public List<LatticeNode> provideOOV(InputText inputText, int offset, boolean hasOtherWords) {
         if (!hasOtherWords) {
             LatticeNode node = createNode();
             node.setParameter(leftId, rightId, cost);
             int length = inputText.getWordCandidateLength(offset);
             String s = inputText.getSubstring(offset, offset + length);
             WordInfo info = new WordInfo(s, (short) length, oovPOSId, s, s, "");
             node.setWordInfo(info);
             return Collections.singletonList(node);
         } else {
             return Collections.emptyList();
         }
     }
````

**Comment by tringn** [comment]
Hi @kazuma-t ,
I am also concerning that issue. Can you have a look on it?
Thank you.

**Comment by kazuma-t** [comment]
I will not automatically output the OOV word itself as readings even if written in Katakana.
That is not good as a default behavior, I think.

But instead, I plan to make a plugin that estimates readings of OOV. Not soon.

**Comment by kazuma-t** [comment]
Another solution is to make your own plugin that inherits from `PathRewritePlugin` and fills OOV's reading.

**Comment by hondv** [comment]
thanks for your answer, @kazuma-t 
i'd customized the plugin `OovProviderPlugin` to fill OOV's reading form, this way is easy to do.
