### ISSUE TITLE
[Question] What are different Parts of Speech values?

### ISSUE THREAD

**Issue by gopalkriagg** [WorksApplications/Sudachi#127]
What are the different elements returned in the parts of speech?
For example, on tokenizing `太郎` we get:
```
太郎	名詞,固有名詞,人名,名,*,*	太郎
```
I want to understand the various parts under:
```
名詞,固有名詞,人名,名,*,*
```
Do each of these comma separated values have a descriptive name?

Sorry, if it is mentioned somewhere in the code! I couldn't find it!

And, thank you for making such an awesome package and making it open source!!

**Comment by sorami** [comment]
Hi,

For this specific case, 

1. `名詞`: Noun (PoS, 1st level category)
2. `固有名詞`: Proper Noun (PoS, 2nd level category)
3. `人名`: Person's Name (PoS, 3rd level category)
4. `名`:  First Name (PoS, 4th level category)
5. (conjugational type)
6. (conjugational form)

***

We follow the dictionary `unidic-mecab 2.1.2` 's Part-of-Speech tag set. There are 6 columns (comma separated as you have shown above). 

For reference, here is a list of UniDic tags (not the official page, summarized by a third person; [UniDic品詞体系 | Yuta Hayashibe](https://hayashibe.jp/tr/mecab/dictionary/unidic/pos)).

The information is pretty complicated (As they are in Japanese, and involves lingustics knowldege). For brief usage, if you do not understand Japanese langauge, I believe you can machine translate each values to get a rough idea of what it means.

**Comment by gopalkriagg** [comment]
Sorami-san, thank you so much for such a quick and detailed answer! It is really helpful. 
Since it answers my question, I will close this issue.
