### ISSUE TITLE
This repository is over its data quota. Purchase more data packs to restore access.

### ISSUE THREAD

**Issue by ichiren1** [WorksApplications/Sudachi#2]
Thank you for publishing a great tool. 

I got this error while trying git lfs pull.

```
$ git lfs pull
Git LFS: (0 of 1 files) 0 B / 493.43 MB
batch response: This repository is over its data quota. Purchase more data packs to restore access.
error: failed to fetch some objects from 'https://github.com/WorksApplications/Sudachi.git/info/lfs'
```

**Comment by ichiren1** [comment]
sorry, my issue is duplicated #1

**Comment by chunleng** [comment]
I think the linked issue #1 was closed because the main issue is resolved.
Can I reopen this issue? Data quota issue is not yet resolved

**Comment by kazuma-t** [comment]
Ok. I reopen this issue.

**Comment by satoshi-murakumo** [comment]
I got same error.
I'd like to try out your project, please tell me how to create `sudachi_lex.csv`.

**Comment by hkazuakey** [comment]
I got the same error. 
Is there any possible workaround?

**Comment by kazuma-t** [comment]
We have purchased data quota. Please try again.

**Comment by ichiren1** [comment]
Thanks, I succeeded in downloading sudachi_lex.csv.

**Comment by hkazuakey** [comment]
Thank you very much!
I also succeeded in downloading the file.
