### ISSUE TITLE
Why not multi sub-module project?

### ISSUE THREAD

**Issue by KengoTODA** [WorksApplications/Sudachi#20]
I found second `pom.xml` in `elasticsearch` directory. Then why we do not use [multi-module project](http://books.sonatype.com/mvnex-book/reference/multimodule.html)?

If we have no clear reason, I will propose a PR to change this project to multi-Module. Here is condition to do so:

* use the same `<version>` for each module (not mandatory but seems possible)
* move `src`, `licenses` and `pom.xml` into `sudachi/src`, `sudachi/licenses` and `sudachi/pom.xml`
    * name of sub directory can be changed to `sudachi-core` or what you prefer

**Comment by kazuma-t** [comment]
I'm debating whether to separate the Elasticsearch plugin from this repository or not. Since it is necessary to adapt to various versions of Elasticseach in the future, it may be better to separate it.

**Comment by KengoTODA** [comment]
I understood. Thank you!

**Comment by KengoTODA** [comment]
> separate the Elasticsearch plugin from this repository 

Do you need my help to make new repository? If you lack permission to do so, I can help you.
And, here is official document about [how to create new repository from sub directory of existing repository](https://help.github.com/articles/splitting-a-subfolder-out-into-a-new-repository/).
