### ISSUE TITLE
「働き」 seems to be incorrectly tokenized as 「働く」

### ISSUE THREAD

**Issue by rbiagini02** [WorksApplications/Sudachi#208]
Tokenizing the following sentence:

働きやすくします

I get the following  results:

```
Surface: 働き - Word id: 299285 - Dictionary form: 働く
PoS: 動詞,一般,*,*,五段-カ行,連用形-一般

Surface: やすく - Word id: 161598 - Dictionary form: やすい
PoS: 接尾辞,形容詞的,*,*,形容詞,連用形-一般

Surface: し - Word id: 67501 - Dictionary form: する
PoS: 動詞,非自立可能,*,*,サ行変格,連用形-一般

Surface: ます - Word id: 148494 - Dictionary form: ます
PoS: 助動詞,*,*,*,助動詞-マス,終止形-一般
```

It is my impression that 働き should not be equated to 働く, the verb.

Using:

- Sudachi 0.7.1
- sudachi-dictionary-20230110-full

**Comment by kazuma-t** [comment]
In the context of the phrase "働きやすくします", "働き" should be interpreted as a compound verb, where the verb "働く" is combined with the adjective "やすい" in its continuative form.

In other words, the adjective "働きやすい" is modifying the verb "する". Therefore, in the sentence "働きやすくします", "働き" should not be interpreted as a noun, but rather as a part of the adjective "働きやすい".
