### ISSUE TITLE
Out of memory error

### ISSUE THREAD

**Issue by NCheng8835** [WorksApplications/Sudachi#211]
百六十四万七千三百四十一,this sentence will cause out of memory,I don't know why.

**Comment by kazuma-t** [comment]
Thank you for your report. But I can't reproduce it. What version and environment are you using?

**Comment by NCheng8835** [comment]
Thank you for your reply, it's my code error

**Comment by NCheng8835** [comment]
I call this function : Tokenizer.tokenizeSentences(String text),no return and OOM

**Comment by kazuma-t** [comment]
I use Windows 11 22H2 / OpenJDK 11.0.2 / Sudachi 0.7.1 / SudachiDict 20230110-core.
```
PS C:\Users\takaoka_k\Desktop\sudachi> echo 百六十四万七千三百四十一 | java '-Dfile.encoding=UTF-8' -jar .\sudachi-0.7.1.jar
百六十四万七千三百四十一        名詞,数詞,*,*,*,*       1647341
EOS
```
