### ISSUE TITLE
IndexOutOfBoundsException caused by short overflow in MeCabOovProvider when the OOV is very long

### ISSUE THREAD

**Issue by eiennohito** [WorksApplications/Sudachi#213]
When OOV is very long (>2^15 bytes), e.g. `'�' * 10923` Sudachi analysis fails with exception caused by MeCabOovPlugin.

Solution: make max length of OOVs ~1024 chars.

**Comment by mh-northlander** [comment]
This particular problem will be solved by #233, as `LatticeNodeImpl.makeOov` sets begin/end directly instead of using oov length 
stored in `WordInfo` as `short` value.
Index form length inside OOV wordInfo is still wrong, but it won't be used.
