### ISSUE TITLE
[Question] What UniDic dictionary version is used to compile the latest Sudachi dictionary

### ISSUE THREAD

**Issue by azagniotov** [WorksApplications/Sudachi#215]
Hello Team, as per subject. 

I am curious as I did not find a clear information about it, if I missed it - I apologize. I would like to know _what version(s)_ of UniDic dictionary is used for the [latest Sudachi dictionary](http://sudachi.s3-website-ap-northeast-1.amazonaws.com/sudachidict/). 

Is it safe to assume that the [latest from Ninjal](https://clrd.ninjal.ac.jp/unidic_archive/2302/) was used to compile the latest dictionary from Sudachi?

Thank you

**Comment by eiennohito** [comment]
No, Sudachi dictionary and Unidic are independent dictionaries.
Sudachi dictionary stems from Unidic but it had already somewhat diverged from it.

Unidic is basically a lexicon for BCCWJ corpus and nothing more. We add neologisms, fix inconsistencies between words and update dictionary based on Japanese language in whole.

**Comment by azagniotov** [comment]
@eiennohito understood! Thank you for clarifying this detail. One more question on this topic - what is Sudachi's approach to releasing newer (updated) dictionaries? e.g.: is it periodic or on a per-need basis?

**Comment by eiennohito** [comment]
We release when the dictionary team has a critical mass of dictionary updates, so more like per-need basis, but we tend to do 2-3 releases a year.

**Comment by azagniotov** [comment]
Thank you, I will close the issue.
