### ISSUE TITLE
[Bug] The default config sudachi.json sets non-existent property joinKanjiNumeric in JoinNumericPlugin

### ISSUE THREAD

**Issue by azagniotov** [WorksApplications/Sudachi#221]
The default config [src/main/resources/sudachi.json#L23-L24](https://github.com/WorksApplications/Sudachi/blob/develop/src/main/resources/sudachi.json#L23-L24) which is bundled with Sudachi JAR `v0.7.3`, it passes non-existent property `joinKanjiNumeric` to the [JoinNumericPlugin.java#L56-L59](https://github.com/WorksApplications/Sudachi/blob/develop/src/main/java/com/worksap/nlp/sudachi/JoinNumericPlugin.java#L56-L59) which in fact uses `enableNormalize` property.

I guess this is not a huge issue because the default value of if the `enableNormalize` does not exist is `true`, which means Kanji numerics get normalized by default
```
@Override
    public void setUp(Grammar grammar) {
        enableNormalize = settings.getBoolean("enableNormalize", true);
        ...
    }
```

But, it would be great if this gets fixed in case if someone does not want to normalize.

**Comment by kazuma-t** [comment]
Thank you for your report. This is an oversight in the improvement of the JoinNumericPlugin. I will make the necessary corrections.
