### ISSUE TITLE
When using "full" dictionary type, the すもももももももものうち is not tokenized correctly 

### ISSUE THREAD

**Issue by azagniotov** [WorksApplications/Sudachi#224]
As per subject. 

I noticed that:

- When I use "core" dictionary type, the `すもももももももものうち` gets tokenized correctly to: `すもも`, `も`, `もも`, `も`, `もも`, `の`, `うち`
- When I use "full" dictionary type, the `すもももももももものうち` gets tokenized correctly to: `すもももももも`, `もも`, `の`, `うち`

**Comment by mosuka** [comment]
Is it because of this Wikipedia entry?

https://ja.m.wikipedia.org/wiki/%E3%81%99%E3%82%82%E3%82%82%E3%82%82%E3%82%82%E3%82%82

**Comment by azagniotov** [comment]
Interesting 🙂 Maybe 🙂 Thank you for bringing this movie to my attention.

**Comment by kawahara-n** [comment]
Thank you for your report.

In the full dictionary, the word "すもももももも" is registered as a single word. It is the title of an comic book. In Sudachi morphological analysis, longer words in the dictionary take precedence. For now, There's nothing we can do about it.
We will consider it as a future task.

**Comment by azagniotov** [comment]
@kawahara-n san, 説明してくれてありがとう！
