### ISSUE TITLE
Can I generate .dic file  using java code? Not using csv file and command line?

### ISSUE THREAD

**Issue by gyf1997** [WorksApplications/Sudachi#228]
And also ,can I open a .dic file using java code and see contents?

**Comment by kazuma-t** [comment]
You can build a dictionary in Java using `DicBuilder`. Please refer to `DictionaryBuilder` for instructions on how to use `DicBuilder`. 
https://github.com/WorksApplications/Sudachi/blob/bbf8ce708e8a195c3afa25b3ecd4ab986e55a621/src/main/java/com/worksap/nlp/sudachi/dictionary/DictionaryBuilder.java#L93

The `DicBuilder.lexcion()` method allows you to read an `InputStream`. Please provide a dictionary source in CSV format.

**Comment by kazuma-t** [comment]
You can refer `DictionaryPrinter` to dump the contents of the binary dictionary.

src/main/java/com/worksap/nlp/sudachi/dictionary/DictionaryPrinter.java

**Comment by gyf1997** [comment]
Thank you for helping me!
