### ISSUE TITLE
distribution zip contains two Sudachi artifacts

### ISSUE THREAD

**Issue by KengoTODA** [WorksApplications/Sudachi#25]
In zip file, we can find `sudachi-0.0.1-SNAPSHOT.jar` and `sudachi-0.1-SNAPSHOT.jar`.
We don't need to package two jar files, so it's better to delete one of them.

**Comment by kazuma-t** [comment]
I cannot find sudachi-0.0.1-SNAPSHOT.jar in sudachi-0.1-SNAPSHOT-executable.zip on my machine or https://oss.sonatype.org/content/repositories/snapshots/com/worksap/nlp/sudachi/0.1-SNAPSHOT/sudachi-0.1-20171109.151743-4-executable.zip

**Comment by KengoTODA** [comment]
Let me confirm, it might be my local specific problem... sorry for confusing you.

**Comment by KengoTODA** [comment]
I confirmed that deployed zip has no problem. I'm going to close this issue.
