### ISSUE TITLE
Version management policy

### ISSUE THREAD

**Issue by KengoTODA** [WorksApplications/Sudachi#27]
Currently version of Sudachi is `0.1-SNAPSHOT` (maybe major = 0, minor = 1), however version of `elasticsearch-sudachi` is `1.0.0-SNAPSHOT` (major = 1, minor = 0, patch = 0). It seems that they use different versioning policy. I recommend you to unify it.

And if you follow [the semver2.0](semver.org/spec/v2.0.0.html), I recommend you to change `1.0.0-SNAPSHOT` to `0.1.0-SNAPSHOT`. `0.x.y` is know as [initial development phase](http://semver.org/spec/v2.0.0.html#how-should-i-deal-with-revisions-in-the-0yz-initial-development-phase) so you can break backward compatibility.

**Comment by kazuma-t** [comment]
Elasticsearch-sudachi is almost fiexed as a plugin. When Sudachi is changed, it will not break backword compatibility.

**Comment by KengoTODA** [comment]
Sorry I cannot catch your meaning, do you mean that it is OK to keep current version management policy?

**Comment by kazuma-t** [comment]
Yes. I will improve Sudachi, but elasticsearch-sudachi needs only bug fix or following the version up of elasticsearch. So I think that the versioning policy of elasticsearch-sudachi don't need to be changed.

**Comment by kazuma-t** [comment]
I've missread your meaning. I will change the version of Sudachi to x.y.z format.

**Comment by KengoTODA** [comment]
OK I see, and I agree that `1.0.0-SNAPSHOT` is enough for analysis-sudachi!

**Comment by KengoTODA** [comment]
Both Sudachi and Elasticsearch-sudachi follow semver2. So I'll close this issue.
