### ISSUE TITLE
Clarify the definition of core and non_core lexicon

### ISSUE THREAD

**Issue by sh0nk** [WorksApplications/Sudachi#34]
At ae2b04782efc9cdd2529d36603f60f227a74b3fe, the dictionary source was split into two files, but there are no clear definition of them and the difference. Could you add it to README?

In addition to that, since all the examples of the named entities on README such as "医薬品安全管理責任者" and "自転車安全整備士" are now included in `non_core.csv`, the default settings don't achieve the three mode difference on README (Both `B` and `C` end up with "医薬品/安全/管理/責任者") and users need to specify `system_full.dic` as system dictionary. It might be better to describe that it requires full dictionary, or to replace them to another example which is included in core dictionary to avoid any confusion.

**Comment by kazuma-t** [comment]
We wrote a rough explanation in README.md.
Thank you for your comment.
