### ISSUE TITLE
[Question] Thread safety

### ISSUE THREAD

**Issue by h6ah4i** [WorksApplications/Sudachi#38]
Hi. I want to create a multi-threaded program using Sudachi. Which class instances can be shared between threads? Should I create every instances for each threads?

I want to know about the following classes;
- `Dictionary` (`JapaneseDictionary`)
- ~~`Tokenizer` (`JapaneseTokenizer`)~~

**Update: I checked the implementation and found out that JapaneseTokenizer mutates it's member variable. So, the tokenizer is not thread safe.**

Thanks.

**Comment by kazuma-t** [comment]
Dictionary's instance can be shared between threads. Tokenizer should be created for each thread.

**Comment by h6ah4i** [comment]
@kazuma-t Thanks for the very quick reply 😄
