### ISSUE TITLE
Do you have motivation to introduce dependency updator?

### ISSUE THREAD

**Issue by KengoTODA** [WorksApplications/Sudachi#43]
Hi, as you may know GitHub recently start providing dependency checker for ruby and node. However Java (Maven) is not supported yet.

If you want to keep your dependency updated, I think https://dependabot.com/ can be good solution. If you need, please notice me then I'll enable it in this repository.

Recently GitHub provides [platform for bots](https://github.com/marketplace), if you want to introduce more like [WIP](https://github.com/apps/wip), it is also welcome to install.

**Comment by kazuma-t** [comment]
Thank you for your introduction.
Our project has only one dependency on javax.json package.  Do I have to check the dependency?

**Comment by KengoTODA** [comment]
Oh, then maybe not. Thanks!
