### ISSUE TITLE
Node missing problem

### ISSUE THREAD

**Issue by mana-ysh** [WorksApplications/Sudachi#45]
In sudachi-0.1.1-SNAPSHOT, this problem may occur in some cases where the input sentence contains successive alphabets.

To reproduce
```
$ echo "阿qd" | java -jar sudachi-0.1.1-SNAPSHOT.jar -d
=== Input dump:
阿qd
=== Lattice dump:
0: 5 5 (null)(0) BOS/EOS 0 0 0: 
1: 0 4 阿Q(1441792) 名詞,固有名詞,人名,一般,*,* 4788 4788 9443: 1 
2: 0 0 (null)(0) BOS/EOS 0 0 0: 0 
Exception in thread "main" java.lang.IllegalStateException: EOS isn't connected to BOS
	at com.worksap.nlp.sudachi.LatticeImpl.getBestPath(LatticeImpl.java:150)
	at com.worksap.nlp.sudachi.JapaneseTokenizer.tokenize(JapaneseTokenizer.java:81)
	at com.worksap.nlp.sudachi.SudachiCommandLine.run(SudachiCommandLine.java:43)
	at com.worksap.nlp.sudachi.SudachiCommandLine.main(SudachiCommandLine.java:148)
```

In this example, it seems that the node which contains the character "d" wasn't generated, so one cannot reach to EOS node.

**Comment by kazuma-t** [comment]
I found the cause. This condition is wrong.
https://github.com/WorksApplications/Sudachi/blob/e33db11003833ac54872a04e584909cee86fe2b0/src/main/java/com/worksap/nlp/sudachi/JapaneseTokenizer.java#L115

But it is a little difficult to fix it without changing outputs. Let me think about it.

**Comment by sorami** [comment]
We still do not have a smart idea to handle this case without compromising the speed.

We currently have an `ignoreError` option which basically `try ... catch` such error case so the program won't stop; https://github.com/WorksApplications/Sudachi/commit/a807b587285a36f41588a3545572d584b1bd4571#diff-3dddad15152221a5bd08547447854ab6

**Comment by sorami** [comment]
With the current dictionary, we only expect this to happen when there's an input `阿Q` followed by alphabets.
