### ISSUE TITLE
Empty surface morpheme(s) before output "´" or "…"

### ISSUE THREAD

**Issue by hiroshi-matsuda** [WorksApplications/Sudachi#60]
SudachiCommandLine outputs empty surface morpheme(s) before output "´" or "…" depending on following context. Seems ACCENT char causes buggy behaviour but HORIZONTAL ELLIPSIS char is normalized for triple DOT chars. The possibility of morpheme having zero length surface should be noted in README.md, I think.
```
java -jar sudachi-0.1.2-SNAPSHOT.jar -a -m A
´
´	補助記号,一般,*,*,*,*	´	´	キゴウ	0
EOS
´´
	空白,*,*,*,*,*	 	 	キゴウ	0
´	補助記号,一般,*,*,*,*				-1	(OOV)
´	補助記号,一般,*,*,*,*	´	´	キゴウ	0
EOS
´。
	空白,*,*,*,*,*	 	 	キゴウ	0
´	補助記号,一般,*,*,*,*				-1	(OOV)
。	補助記号,句点,*,*,*,*	。	。	キゴウ	0
EOS
´あ
´	補助記号,一般,*,*,*,*	´	´	キゴウ	0
あ	感動詞,一般,*,*,*,*	あっ	あ	ア	0
EOS
…   
	補助記号,句点,*,*,*,*	.	.	キゴウ	0
	補助記号,句点,*,*,*,*	.	.	キゴウ	0
…	補助記号,句点,*,*,*,*	.	.	キゴウ	0
EOS
```

**Comment by kazuma-t** [comment]
`´` (U+00B4) is normalized to U+0020 + U+0301 by NKFC. It's in the specifications.
It is also in the specifications that `…` (U+2026) is converted to `...` (U+002E x 3), but the position of the original character is not expected. I'll try to fix it.
