### ISSUE TITLE
Overflow can occur when writing headwordLength to the system dictionary.

### ISSUE THREAD

**Issue by msnoigrs** [WorksApplications/Sudachi#77]
There is a long headword line more than 255 bytes in core_lex.csv.

The latest core_lex.csv: line 49605
```
あなたの幸せが私の幸せ世の為人の為人類幸福繋がり創造即ち我らの使命なり今まさに変革の時ここに熱き魂と愛と情鉄の勇気と利他の精神を持つ者が結集せり日々感謝喜び笑顔繋がりを確かな一歩とし地球の永続を約束する公益の志溢れる我らの足跡に歴史の花が咲くいざゆかん浪漫輝く航海へ
```
This headword is 399 bytes in UTF-8.

It will store in short(2 bytes) when reading from CSV.
https://github.com/WorksApplications/Sudachi/blob/423d07087e60c48a65dd955b85100c37f825c7ea/src/main/java/com/worksap/nlp/sudachi/dictionary/DictionaryBuilder.java#L163

But it will cast to byte(1 byte) when writing to the dictionary.
https://github.com/WorksApplications/Sudachi/blob/423d07087e60c48a65dd955b85100c37f825c7ea/src/main/java/com/worksap/nlp/sudachi/dictionary/DictionaryBuilder.java#L330

Overflow can occur.

**Comment by kazuma-t** [comment]
Thank you for your report.
I fixed it in #78.
