### ISSUE TITLE
Words w/o normalization are ignored in user dictionary

### ISSUE THREAD

**Issue by kazuma-t** [WorksApplications/Sudachi#83]
The first column of a source of user dictionary is a headword for TRIE.
Because input texts are normalized by `DefaultInputTextPlugin`, the headwords must be normalized in the same way.
Normalize by `DefaultInputTextPlugin` when build dictionary, or add a caution to the document.

**Comment by mh-northlander** [comment]
Caution is added by https://github.com/WorksApplications/Sudachi/commit/a6705cc97606967499c873e3a96a607071e6ddbf
